# Generated by Django 2.0.4 on 2018-04-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='field',
            field=models.CharField(default='New Title', max_length=255),
        ),
    ]
