# Generated by Django 2.0.4 on 2018-04-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180405_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(default='New Title', max_length=255, unique=True),
        ),
    ]
