# Generated by Django 2.0.4 on 2018-04-05 03:51

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180405_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='author_email',
            field=models.CharField(blank=True, max_length=240, null=True, validators=[blog.validators.validate_author_email, blog.validators.validate_justin]),
        ),
    ]
